export const Constants = {
  SHOW_DIALOG: "SHOW_DIALOG",
  HIDE_DIALOGE: "HIDE_DIALOGE",
  UPDATE_AUTHORIZATION: "UPDATE_AUTHORIZATION ",
  //Auth constant
  LOGIN_REQUEST: "LOGIN_REQUEST",
  LOGIN_LOADING: "LOGIN_LOADING",
  LOGIN_SUCCESS: "LOGIN_SUCCESS",
  LOGIN_DATA: "LOGIN_DATA",
  LOGIN_ERROR: "LOGIN_ERROR",

  LOGOUT_REQUEST: "LOGOUT_REQUEST",
  LOGOUT_LOADING: "LOGOUT_LOADING",
  LOGOUT_SUCCESS: "LOGOUT_SUCCESS",
  LOGOUT_ERROR: "LOGOUT_ERROR",

  REGISTER_REQUEST: "REGISTER_REQUEST",
  REGISTER_LOADING: "REGISTER_LOADING",
  REGISTER_SUCCESS: "REGISTER_SUCCESS",
  REGISTER_ERROR: "REGISTER_ERROR",

  ROLE_SELECT: "ROLE_SELECT",

  SOCIAL_LOGIN_REQUEST: "SOCIAL_LOGIN_REQUEST",
  SOCIAL_LOGIN_LOADING: "SOCIAL_LOGIN_LOADING",
  SOCIAL_LOGIN_SUCCESS: "SOCIAL_LOGIN_SUCCESS",
  SOCIAL_LOGIN_ERROR: "SOCIAL_LOGIN_ERROR",

  //Class constant
  GET_CLASS_REQUEST: "GET_CLASS_REQUEST",
  GET_CLASS_LOADING: "GET_CLASS_LOADING",
  GET_CLASS_SUCCESS: "GET_CLASS_SUCCESS",
  GET_CLASS_ERROR: "GET_CLASS_ERROR",

  GET_INSTRUCTOR_CLASS_REQUEST: "GET_INSTRUCTOR_CLASS_REQUEST",
  GET_INSTRUCTOR_CLASS_LOADING: "GET_INSTRUCTOR_CLASS_LOADING",
  GET_INSTRUCTOR_CLASS_SUCCESS: "GET_INSTRUCTOR_CLASS_SUCCESS",
  GET_INSTRUCTOR_CLASS_ERROR: "GET_INSTRUCTOR_CLASS_ERROR",

  DELETE_INSTRUCTOR_CLASS_REQUEST: "DELETE_INSTRUCTOR_CLASS_REQUEST",
  DELETE_INSTRUCTOR_CLASS_LOADING: "DELETE_INSTRUCTOR_CLASS_LOADING",
  DELETE_INSTRUCTOR_CLASS_SUCCESS: "DELETE_INSTRUCTOR_CLASS_SUCCESS",
  DELETE_INSTRUCTOR_CLASS_ERROR: "DELETE_INSTRUCTOR_CLASS_ERROR",

  SINGLE_CLASS_REQUEST: "SINGLE_CLASS_REQUEST",
  SINGLE_CLASS_LOADING: "SINGLE_CLASS_LOADING",
  SINGLE_CLASS_SUCCESS: "SINGLE_CLASS_SUCCESS",
  SINGLE_CLASS_ERROR: "SINGLE_CLASS_ERROR",

  DELETE_CLASS_REQUEST: "DELETE_CLASS_REQUEST",
  DELETE_CLASS_LOADING: "DELETE_CLASS_LOADING",
  DELETE_CLASS_SUCCESS: "DELETE_CLASS_SUCCESS",
  DELETE_CLASS_ERROR: "DELETE_CLASS_ERROR",

  EDIT_CLASS_REQUEST: "EDIT_CLASS_REQUEST",
  EDIT_CLASS_LOADING: "EDIT_CLASS_LOADING",
  EDIT_CLASS_SUCCESS: "EDIT_CLASS_SUCCESS",
  EDIT_CLASS_ERROR: "EDIT_CLASS_ERROR",

  CREATE_CLASS_REQUEST: "CREATE_CLASS_REQUEST",
  CREATE_CLASS_LOADING: "CREATE_CLASS_LOADING",
  CREATE_CLASS_SUCCESS: "CREATE_CLASS_SUCCESS",
  CREATE_CLASS_ERROR: "CREATE_CLASS_ERROR",

  GET_CATEGORY_REQUEST: "GET_CATEGORY_REQUEST",
  GET_CATEGORY_LOADING: "GET_CATEGORY_LOADING",
  GET_CATEGORY_SUCCESS: "GET_CATEGORY_SUCCESS",
  GET_CATEGORY_ERROR: "GET_CATEGORY_ERROR",

  INSTRUCTOR_CLASS_BYID_REQUEST: "INSTRUCTOR_CLASS_BYID_REQUEST",
  INSTRUCTOR_CLASS_BYID_LOADING: "INSTRUCTOR_CLASS_BYID_LOADING",
  INSTRUCTOR_CLASS_BYID_SUCCESS: "INSTRUCTOR_CLASS_BYID_SUCCESS",
  INSTRUCTOR_CLASS_BYID_ERROR: "INSTRUCTOR_CLASS_BYID_ERROR",

  UPDATE_INS_CLASS_REQUEST: "UPDATE_INS_CLASS_REQUEST",
  UPDATE_INS_CLASS_LOADING: "UPDATE_INS_CLASS_LOADING",
  UPDATE_INS_CLASS_SUCCESS: "UPDATE_INS_CLASS_SUCCESS",
  UPDATE_INS_CLASS_ERROR: "UPDATE_INS_CLASS_ERROR",

  GET_CLASS_BYCAT_REQUEST: "GET_CLASS_BYCAT_REQUEST",
  GET_CLASS_BYCAT_LOADING: "GET_CLASS_BYCAT_LOADING",
  GET_CLASS_BYCAT_SUCCESS: "GET_CLASS_BYCAT_SUCCESS",
  GET_CLASS_BYCAT_ERROR: "GET_CLASS_BYCAT_ERROR",

  // AUTH CONSTANT
  VERIFY_OTP_REQUEST: "VERIFY_OTP_REQUEST",
  VERIFY_OTP_LOADING: "VERIFY_OTP_LOADING",
  VERIFY_OTP_SUCCESS: "VERIFY_OTP_SUCCESS",
  VERIFY_OTP_ERROR: "VERIFY_OTP_ERROR",

  SWITCH_USER_REQUEST: "SWITCH_USER_REQUEST",
  SWITCH_USER_LOADING: "SWITCH_USER_LOADING",
  SWITCH_USER_SUCCESS: "SWITCH_USER_SUCCESS",
  SWITCH_USER_ERROR: "SWITCH_USER_ERROR",

  FORGOT_PASSWORD_REQUEST: "FORGOT_PASSWORD_REQUEST",
  FORGOT_PASSWORD_LOADING: "FORGOT_PASSWORD_LOADING",
  FORGOT_PASSWORD_SUCCESS: "FORGOT_PASSWORD_SUCCESS",
  FORGOT_PASSWORD_ERROR: "FORGOT_PASSWORD_ERROR",

  RESEND_OTP_REQUEST: "RESEND_OTP_REQUEST",
  RESEND_OTP_LOADING: "RESEND_OTP_LOADING",
  RESEND_OTP_SUCCESS: "RESEND_OTP_SUCCESS",
  RESEND_OTP_ERROR: "RESEND_OTP_ERROR",

  RESET_PASSWORD_REQUEST: "RESET_PASSWORD_REQUEST",
  RESET_PASSWORD_LOADING: "RESET_PASSWORD_LOADING",
  RESET_PASSWORD_SUCCESS: "RESET_PASSWORD_SUCCESS",
  RESET_PASSWORD_ERROR: "RESET_PASSWORD_ERROR",

  UPDATE_TEMP_DATA: "UPDATE_TEMP_DATA",

  IMAGE_UPLOAD_REQUEST: "IMAGE_UPLOAD_REQUEST",
  IMAGE_UPLOAD_ERROR: "IMAGE_UPLOAD_ERROR",
  IMAGE_UPLOAD_SUCCESS: "IMAGE_UPLOAD_SUCCESS",
  IMAGE_UPLOAD_LOADING: "IMAGE_UPLOAD_LOADING",

  GET_PROFILE_REQUEST: "GET_PROFILE_REQUEST",
  GET_PROFILE_ERROR: "GET_PROFILE_ERROR",
  GET_PROFILE_SUCCESS: "GET_PROFILE_SUCCESS",
  GET_PROFILE_LOADING: "GET_PROFILE_LOADING",

  UPDATE_PROFILE_REQUEST: "UPDATE_PROFILE_REQUEST",
  UPDATE_PROFILE_ERROR: "UPDATE_PROFILE_ERROR",
  UPDATE_PROFILE_SUCCESS: "UPDATE_PROFILE_SUCCESS",
  UPDATE_PROFILE_LOADING: "UPDATE_PROFILE_LOADING",

  CHANGE_PASSWORD_REQUEST: "CHANGE_PASSWORD_REQUEST",
  CHANGE_PASSWORD_ERROR: "CHANGE_PASSWORD_ERROR",
  CHANGE_PASSWORD_SUCCESS: "CHANGE_PASSWORD_SUCCESS",
  CHANGE_PASSWORD_LOADING: "CHANGE_PASSWORD_LOADING",

  ADD_BANK_REQUEST: "ADD_BANK_REQUEST",
  ADD_BANK_ERROR: "ADD_BANK_ERROR",
  ADD_BANK_SUCCESS: "ADD_BANK_SUCCESS",
  ADD_BANK_LOADING: "ADD_BANK_LOADING",

  GET_ABOUT_REQUEST: "GET_ABOUT_REQUEST",
  GET_ABOUT_ERROR: "GET_ABOUT_ERROR",
  GET_ABOUT_SUCCESS: "GET_ABOUT_SUCCESS",
  GET_ABOUT_LOADING: "GET_ABOUT_LOADING",

  GET_FAQ_REQUEST: "GET_FAQ_REQUEST",
  GET_FAQ_LOADING: "GET_FAQ_LOADING",
  GET_FAQ_ERROR: "GET_FAQ_ERROR",
  GET_FAQ_SUCCESS: "GET_FAQ_SUCCESS",

  // Booking Constants

  CREATE_BOOKING_REQUEST: "CREATE_BOOKING_REQUEST",
  CREATE_BOOKING_LOADING: "CREATE_BOOKING_LOADING",
  CREATE_BOOKING_ERROR: "CREATE_BOOKING_ERROR",
  CREATE_BOOKING_SUCCESS: "CREATE_BOOKING_SUCCESS",

  GET_CUST_BOOKING_REQUEST: "GET_CUST_BOOKING_REQUEST",
  GET_CUST_BOOKING_LOADING: "GET_CUST_BOOKING_LOADING",
  GET_CUST_BOOKING_ERROR: "GET_CUST_BOOKING_ERROR",
  GET_CUST_BOOKING_SUCCESS: "GET_CUST_BOOKING_SUCCESS",

  GET_CUST_BYID_BOOKING_REQUEST: "GET_CUST_BYID_BOOKING_REQUEST",
  GET_CUST_BYID_BOOKING_LOADING: "GET_CUST_BYID_BOOKING_LOADING",
  GET_CUST_BYID_BOOKING_ERROR: "GET_CUST_BYID_BOOKING_ERROR",
  GET_CUST_BYID_BOOKING_SUCCESS: "GET_CUST_BYID_BOOKING_SUCCESS",

  GET_INST_BOOKING_REQUEST: "GET_INST_BOOKING_REQUEST",
  GET_INST_BOOKING_LOADING: "GET_INST_BOOKING_LOADING",
  GET_INST_BOOKING_ERROR: "GET_INST_BOOKING_ERROR",
  GET_INST_BOOKING_SUCCESS: "GET_INST_BOOKING_SUCCESS",

  CUST_CANCEL_BOOKING_REQUEST: "CUST_CANCEL_BOOKING_REQUEST",
  CUST_CANCEL_BOOKING_LOADING: "CUST_CANCEL_BOOKING_LOADING",
  CUST_CANCEL_BOOKING_ERROR: "CUST_CANCEL_BOOKING_ERROR",
  CUST_CANCEL_BOOKING_SUCCESS: "CUST_CANCEL_BOOKING_SUCCESS",

  ADD_RATING_REQUEST: "ADD_RATING_REQUEST",
  ADD_RATING_LOADING: "ADD_RATING_LOADING",
  ADD_RATING_ERROR: "ADD_RATING_ERROR",
  ADD_RATING_SUCCESS: "ADD_RATING_SUCCESS",

  CREATE_REPORT_REQUEST: "CREATE_REPORT_REQUEST",
  CREATE_REPORT_LOADING: "CREATE_REPORT_LOADING",
  CREATE_REPORT_ERROR: "CREATE_REPORT_ERROR",
  CREATE_REPORT_SUCCESS: "CREATE_REPORT_SUCCESS",

  GET_DISCOUNT_LOADING: "GET_DISCOUNT_LOADING",
  GET_DISCOUNT_SUCCESS: "GET_DISCOUNT_SUCCESS",
  GET_DISCOUNT_ERROR: "GET_DISCOUNT_ERROR",
  GET_DISCOUNT_REQUEST: "GET_DISCOUNT_REQUEST",

  //Membership constants

  ADD_MEMBER_REQUEST: "ADD_MEMBER_REQUEST",
  ADD_MEMBER_LOADING: "ADD_MEMBER_LOADING",
  ADD_MEMBER_ERROR: "ADD_MEMBER_ERROR",
  ADD_MEMBER_SUCCESS: "ADD_MEMBER_SUCCESS",

  GET_MEMBER_REQUEST: "GET_MEMBER_REQUEST",
  GET_MEMBER_LOADING: "GET_MEMBER_LOADING",
  GET_MEMBER_ERROR: "GET_MEMBER_ERROR",
  GET_MEMBER_SUCCESS: "GET_MEMBER_SUCCESS",

  DELETE_MEMBER_REQUEST: "DELETE_MEMBER_REQUEST",
  DELETE_MEMBER_LOADING: "DELETE_MEMBER_LOADING",
  DELETE_MEMBER_ERROR: "DELETE_MEMBER_ERROR",
  DELETE_MEMBER_SUCCESS: "DELETE_MEMBER_SUCCESS",

  UPDATE_MEMBER_REQUEST: "UPDATE_MEMBER_REQUEST",
  UPDATE_MEMBER_LOADING: "UPDATE_MEMBER_LOADING",
  UPDATE_MEMBER_ERROR: "UPDATE_MEMBER_ERROR",
  UPDATE_MEMBER_SUCCESS: "UPDATE_MEMBER_SUCCESS",

  GET_SINGLE_MEMBER_REQUEST: "GET_SINGLE_MEMBER_REQUEST",
  GET_SINGLE_MEMBER_ERROR: "GET_SINGLE_MEMBER_ERROR",
  GET_SINGLE_MEMBER_LOADING: "GET_SINGLE_MEMBER_LOADING",
  GET_SINGLE_MEMBER_SUCCESS: "GET_SINGLE_MEMBER_SUCCESS",

  GET_INST_SUBSCRIPTION_REQUEST: "GET_INST_SUBSCRIPTION_REQUEST",
  GET_INST_SUBSCRIPTION_ERROR: "GET_INST_SUBSCRIPTION_ERROR",
  GET_INST_SUBSCRIPTION_LOADING: "GET_INST_SUBSCRIPTION_LOADING",
  GET_INST_SUBSCRIPTION_SUCCESS: "GET_INST_SUBSCRIPTION_SUCCESS",

  BUY_SUBSCRIPTION_REQUEST: "BUY_SUBSCRIPTION_REQUEST",
  BUY_SUBSCRIPTION_ERROR: "BUY_SUBSCRIPTION_ERROR",
  BUY_SUBSCRIPTION_LOADING: "BUY_SUBSCRIPTION_LOADING",
  BUY_SUBSCRIPTION_SUCCESS: "BUY_SUBSCRIPTION_SUCCESS",

  GET_USER_MEMBER_REQUEST: "GET_USER_MEMBER_REQUEST",
  GET_USER_MEMBER_LOADING: "GET_USER_MEMBER_LOADING",
  GET_USER_MEMBER_ERROR: "GET_USER_MEMBER_ERROR",
  GET_USER_MEMBER_SUCCESS: "GET_USER_MEMBER_SUCCESS",

  // DASHBOARD
  GET_USER_DASHBOARD_REQUEST: "GET_USER_DASHBOARD_REQUEST",
  GET_USER_DASHBOARD_LOADING: "GET_USER_DASHBOARD_LOADING",
  GET_USER_DASHBOARD_ERROR: "GET_USER_DASHBOARD_ERROR",
  GET_USER_DASHBOARD_SUCCESS: "GET_USER_DASHBOARD_SUCCESS",

  // WISHLIST
  ADD_WISHLIST_REQUEST: "ADD_WISHLIST_REQUEST",
  ADD_WISHLIST_LOADING: "ADD_WISHLIST_LOADING",
  ADD_WISHLIST_ERROR: "ADD_WISHLIST_ERROR",
  ADD_WISHLIST_SUCCESS: "ADD_WISHLIST_SUCCESS",

  GET_WISHLIST_REQUEST: "GET_WISHLIST_REQUEST",
  GET_WISHLIST_LOADING: "GET_WISHLIST_LOADING",
  GET_WISHLIST_ERROR: "GET_WISHLIST_ERROR",
  GET_WISHLIST_SUCCESS: "GET_WISHLIST_SUCCESS",

  // Instructor Dashboard
  GET_INT_DASHBOARD_REQUEST: "GET_INT_DASHBOARD_REQUEST",
  GET_INT_DASHBOARD_SUCCESS: "GET_INT_DASHBOARD_SUCCESS",
  GET_INT_DASHBOARD_ERROR: "GET_INT_DASHBOARD_ERROR",
  GET_INT_DASHBOARD_LOADING: "GET_INT_DASHBOARD_LOADING",

  // socket
  UPDATE_SOCKET_CONNECTION: "UPDATE_SOCKET_CONNECTION",

  //chat
  GET_CHAT_LIST_REQUEST: "GET_CHAT_LIST_REQUEST",
  GET_CHAT_LIST_LOADING: "GET_CHAT_LIST_LOADING",
  GET_CHAT_LIST_ERROR: "GET_CHAT_LIST_ERROR",
  GET_CHAT_LIST_SUCCESS: "GET_CHAT_LIST_SUCCESS",
  GET_CHAT_LIST_UPDATE: "GET_CHAT_LIST_UPDATE",

  GET_CHAT_HISTORY_REQUEST: "GET_CHAT_HISTORY_REQUEST",
  GET_CHAT_HISTORY_LOADING: "GET_CHAT_HISTORY_LOADING",
  GET_CHAT_HISTORY_ERROR: "GET_CHAT_HISTORY_ERROR",
  GET_CHAT_HISTORY_SUCCESS: "GET_CHAT_HISTORY_SUCCESS",
  ADD_TO_CHAT: "ADD_TO_CHAT",
  REMOVE_FROM_CHAT: "REMOVE_FROM_CHAT",

  // Notification
  NOTIFICATION_LIST_REQUEST: "NOTIFICATION_LIST_REQUEST",
  NOTIFICATION_LIST_SUCCESS: "NOTIFICATION_LIST_SUCCESS",
  NOTIFICATION_LIST_ERROR: "NOTIFICATION_LIST_ERROR",
  NOTIFICATION_LIST_LOADING: "NOTIFICATION_LIST_LOADING",
};
