export const Modules = {
  LOGIN: "LOGIN",
  SIGNUP: "SIGNUP",
  VERIFY: "VERIFY",
  DATE: "DATE",
  TIME: "TIME",
  SEATS: "SEATS",
  FILTER: "FILTER",
  FORGOT_PASSWORD: "FORGOT_PASSWORD",
  DELETE: "DELETE",
  CANCEL_BOOKING: "CANCEL_BOOKING",
  DISCOUNT: "DISCOUNT",
  DELETE_MEMBERSHIP: "DELETE_MEMBERSHIP",
};
